### ISSUE TITLE
Reading request headers

### ISSUE THREAD

**Issue by deann88** [dselivanov/RestRserve#15]
I have been trying to get request headers with the following code:
```
ApiReadHeader <- function(request, response) {
     response$body <-  request$headers[["TenantID"]]
     response$content_type <- "application/json"
     response$headers <- character(0)
     response$status_code <- 200L
     forward()
}
RestRserveApp <- RestRserve::RestRserveApplication$new()
RestRserveApp$add_get(path = "/api/readheader", FUN = ApiReadHeader)
RestRserveApp$run(8001)
```

And the following curl request : 
```curl -X GET "http://localhost:8001/api/readheader" -H "TenantID: 5a8d27c232f69a38f467517d"```

I expected the server to respond with `5a8d27c232f69a38f467517d`, however I got 
```
Error in user code: subscript out of bounds
Call: request$headers[["TenantID"]]
Tracebeck:
  FUN(request, response)
```

**What am I doing wrong?**
**And what is the best way to debug RestRserveApplication?**

I had trouble doing that so I tried returning request's headers, quaries, and bodies to be able to have a look at them and their structure. 

I also tried:  `response$body <-  str(request$headers)` however it returns and R error again.

Help is appreciated.
Thanks.

**Comment by dselivanov** [comment]
Hi. `RestRserve` is still very "work in progress" and many things are not very well documented. In this particular case the issue is that internally during headers processing we make put them to lower case. So I believe `response$body <- request$headers[["tenantid"]]` should work.

I don't have a good recipe on how to debug. What I do at the moment - I write logs with [futile.logger](https://cran.r-project.org/web/packages/futile.logger/index.html) package.

**Comment by dselivanov** [comment]
Thanks. I will appreciate if you can report any issues you will encounter.
